# Generated by Django 4.2.5 on 2023-09-15 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=225, unique=True)),
                ('title', models.CharField(max_length=225)),
                ('text', models.TextField()),
                ('is_published', models.BooleanField(default=django.utils.timezone.now)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
